const mongoose = require("mongoose");
const objectid = mongoose.Schema.Types.ObjectId;
const Employee_OwnerSchema = mongoose.Schema(
        {
                name: { type: String, default: "" },
                refferalCode: { type: String, default: "" },
                wallet: { type: Number, default: 0, },
                email: { type: String, default: "" },
                image: { type: String, default: "" },
                password: { type: String, default: "" },
                confirmpassword: { type: String, default: "" },
                phone: { type: String, },
                otp: { type: String, default: "", },
                otpVerification: { type: Boolean, default: false, },
                otpExpire: { type: Date, },
                role: { type: String, enum: ["DRIVER", "EMPLOYER", "ADMIN"], },
                companyType: { type: String, enum: ["COMPANY", "INDIVISUAL"], },
                profileComplete: { type: Boolean, default: false, },
                mobileNumber: { type: String, },
                gender: { type: String, default: "", },
                firstName: { type: String, default: "", },
                lastName: { type: String, default: "", },
                ResumeTitle: { type: String, default: "", },
                details: { type: String },
                location: { type: objectid, ref: "location", },
                exactAddress: { type: String, default: "", },
                website: { type: String, default: "", },
                category: { type: objectid, ref: "category", },
                language: { type: objectid, ref: "different_Languages", },
                militaryService: { type: String, default: "", },
                DateOfBirth: { type: String, default: "", },
                licienceNumber: { type: String, default: "", },
                email: { type: String, default: "", },
                interest: { type: String, default: "", },
                experience: [{
                        companyName: { type: String, default: "", },
                        jobTitle: { type: String, default: "", },
                        vehicletype: { type: objectid, ref: "vehicletype", },
                        starttime: { type: String, default: "", },
                        endtime: { type: String, default: "", },
                        Status: { type: String, default: "", },
                }],
                frontImage: { type: String, default: "", },
                backImage: { type: String, default: "", },
                photoUpload: { type: String, default: "", },
                jobServicesId: [{ type: objectid, ref: "jobService", }],
                employerAction: { type: String, default: "", },
                subscriptionId: { type: objectid, ref: "subscription", },
                subscriptionVerification: { type: Boolean, default: false, },
                subscriptionExpire: { type: Date, },
                viewed: { type: Boolean, default: false, },
                followers: [{ type: objectid, ref: "users", }],
                following: [{ type: objectid, ref: "users", }],
                followerCount: { type: Number, default: 0, },
                followingCount: { type: Number, default: 0, },
                jobPostCount: { type: Number, default: 0, },
        },
        {
                timestamps: true,
        }
);

module.exports = mongoose.model("users", Employee_OwnerSchema);
